// ============================================================
// Every mini-game ultimately reports one number (lib/challengeScores.js)
// and this registry says how to turn that into a ranking:
//   "score-desc" — higher number wins (points, bricks broken, etc.)
//   "time-asc"   — lower number wins (a finish time in ms)
// Ties in EITHER direction are broken by who reported their score
// first — this is also exactly Trivia's requested tiebreaker (fastest
// answers wins), it just turns out to be the right default for every
// other game too (whoever locked in their result first, under equal
// scores, gets the edge).
// ============================================================

export const GAME_TYPES = {
  MANUAL: "manual",
  MATCH3: "match3",
  FROGGER: "frogger",
  WORDSCRAMBLE: "wordscramble",
  MAZE2D: "maze2d",
  MAZEINVISIBLE: "mazeinvisible",
  MAZETRIVIA: "mazetrivia",
  FARKLE: "farkle",
  TRIVIA: "trivia",
  BREAKOUT: "breakout",
  PLINKO: "plinko",
  SPOTDIFF: "spotdiff",
  WHACKMOLE: "whackmole",
  BASKETBALL: "basketball",
  STACK: "stack",
  STOCKMARKET: "stockmarket",
  ARTAUCTION: "artauction",
  SEASONTRIVIA: "seasontrivia",
  TIMELINE: "timeline",
  MYSTERYBUTTON: "mysterybutton",
  SIMON: "simon",
  BOGGLE: "boggle",
  DEALORNODEAL: "dealornodeal",
  METRONOME: "metronome",
  PIT: "pit",
  WHOSAIDIT: "whosaidit",
  MASQUERADE: "masquerade",
  CLOSETO20: "closeto20",
  SNAKE: "snake",
  MINESWEEPER: "minesweeper",
  STROOP: "stroop",
  REDLIGHTGREENLIGHT: "redlightgreenlight",
  SLIDINGPUZZLE: "slidingpuzzle",
  LIFESTAPESTRY: "lifestapestry",
  LIFESTAPESTRYTV: "lifestapestrytv",
  TORCHED: "torched",
  CHAINS: "chains",
  LABYRINTH: "labyrinth",
  ORACLESSEAL: "oraclesseal",
  HERMESGRASP: "hermesgrasp",
  PANDORASBOXES: "pandorasboxes",
  MUSICALCHAIRS: "musicalchairs",
  FLOOR: "floor",
  GOLDENFLEECE: "goldenfleece",
  RIVERSTYX: "riverstyx",
  WINEDARKSEA: "winedarksea",
  MINOTAURMAZE: "minotaurmaze",
  MAJORITYRULES: "majorityrules",
  MAJORITYRULESTV: "majorityrulestv",
  TRIGGERHAPPY: "triggerhappy",
  TRIGGERHAPPYTV: "triggerhappytv",
  GODSANDGAMBITS: "godsandgambits",
  DIVINERSDICE: "divinersdice",
  SPLITFRICTION: "splitfriction",
  CROWNS: "crowns",
  CROWNSTV: "crownstv",
  POSEIDONSPOOL: "poseidonspool",
  POSEIDONSPOOLTV: "poseidonspooltv",
  PYTHIASDICE: "pythiasdice",
  NAIADSAQUEDUCT: "naiadsaqueduct",
  PANSPANIC: "panspanic",
  DELPHISDIG: "delphisdig",
  MIDASHOARD: "midashoard",
  CHARIOTS: "chariots",
  SCYLLASSTRAIT: "scyllasstrait",
};

export const GAME_REGISTRY = {
  // No longer offered as a choice in the host's game picker (see
  // ChallengeHost.jsx) — kept here, not deleted, purely so any PAST
  // challenge that already used it (challenge history, ceremony
  // recaps, ...) still resolves to a real label/icon/blurb instead of
  // showing up blank or broken.
  manual: { label: "Manual / In-Person", icon: "📋", rank: "manual", defaultDurationSec: 900, blurb: "Run any real-world battle yourselves; enter finishing order by hand." },
  match3: { label: "Match 3", icon: "💎", rank: "score-desc", defaultDurationSec: 180, category: "Arcade", blurb: "Swap adjacent gems to clear lines of 3+. Highest score when time's up wins." },
  frogger: { label: "Frogger", icon: "🐸", rank: "score-desc", defaultDurationSec: 180, config: { lives: 3 }, category: "Arcade", blurb: "Guide 5 frogs home across traffic. Forward hops, home arrivals, time bonuses, and bonus lady frogs/flies all score — highest total wins." },
  wordscramble: { label: "Word Scramble", icon: "🔤", rank: "time-asc", defaultDurationSec: 300, category: "Word", blurb: "Unscramble your own set of 7 floating, fading letters. Fastest to solve all 7 wins." },
  wordscrambletv: { label: "Word Scramble — Big Screen", icon: "📺🔤", rank: "score-desc", defaultDurationSec: 300, category: "Word", blurb: "Big Screen Mode only. A shared pool of scrambled words on the TV — solve any of them from your phone. Guess one right and it's replaced by a fresh word. Whoever's solved the most when time's up wins." },
  maze2d: { label: "2D Maze", icon: "🧩", rank: "time-asc", defaultDurationSec: 300, config: { size: 11 }, category: "Maze", blurb: "Navigate from start to finish, fog-of-war style — only where you've walked (and the goal) is visible. Fastest solve wins." },
  mazeinvisible: { label: "Invisible Maze", icon: "🕶️", rank: "time-asc", defaultDurationSec: 300, config: { size: 15 }, category: "Maze", blurb: "Collect 3 gems in order. Toggle between viewing the maze (can't move) and moving blind (walls invisible, wall bumps cost time). Fastest wins." },
  mazetrivia: { label: "Trivia Maze", icon: "🔑", rank: "time-asc", defaultDurationSec: 300, config: { size: 15 }, category: "Maze", blurb: "Collect 5 gems in order. Each has a direct shortcut gated by a trivia question — answer right for instant access, wrong and you navigate the maze the long way. Fastest wins." },
  farkle: { label: "Farkle", icon: "🎲", rank: "score-desc", defaultDurationSec: 300, category: "Luck", blurb: "Solo dice scoring game — bank points or push your luck. Highest banked score wins." },
  trivia: { label: "Trivia", icon: "❓", rank: "score-desc", defaultDurationSec: 130, config: { questions: 10, secPerQuestion: 10 }, category: "Trivia", blurb: "See each category, then choose your difficulty — Easy (1pt), Medium (2pts), or Hard (3pts). Highest total wins; fastest answers break ties." },
  breakout: { label: "Breakout", icon: "🧱", rank: "score-desc", defaultDurationSec: 180, config: { lives: 3 }, category: "Arcade", blurb: "Break bricks with a paddle and ball, after a 3-2-1 countdown. 3 lives — most bricks broken wins." },
  plinko: { label: "Plinko", icon: "🔴", rank: "score-desc", defaultDurationSec: 120, config: { shots: 3 }, category: "Arcade", blurb: "Drop 3 chips through the pegs into scoring slots. Highest total wins." },
  spotdiff: { label: "Spot the Difference", icon: "🔍", rank: "score-desc", defaultDurationSec: 180, config: { differences: 5 }, category: "Visual", blurb: "Find all 5 differences between two scenes. Fastest to find them all wins." },
  whackmole: { label: "Whack-a-Mole", icon: "🔨", rank: "score-desc", defaultDurationSec: 90, category: "Speed", blurb: "90 seconds, same standardized mole sequence for everyone. Gold moles are +5, red moles are -3, plain moles are +1. Most points wins." },
  simon: { label: "Simon", icon: "🔴", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "Watch a growing sequence of 4 pads, then repeat it. Every round adds one more step — most rounds completed before a mistake wins." },
  simontv: { label: "Simon — Big Screen", icon: "📺🔴", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "Big Screen Mode only. One shared sequence, growing each round, played on the TV for everyone at once — repeat it from your phone. A wrong tap eliminates you instantly. Last player standing wins." },
  eyesinthesystem: { label: "Eyes in the System", icon: "👁", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "8 rounds — three zones scattered with colored eyes, spot which zone has the most of the called color. Most correct wins; fastest breaks a tie." },
  eyesinthesystemtv: { label: "Eyes in the System — Big Screen", icon: "📺👁", rank: "score-desc", defaultDurationSec: 480, category: "Puzzle", blurb: "Big Screen Mode only. Two players face off at a time on the shared TV — first to correctly spot which zone has the most of the called color wins. The winner picks the next two to face off. Last one never eliminated wins." },
  balloono: { label: "Balloono", icon: "💧", rank: "score-desc", defaultDurationSec: 600, category: "Speed", blurb: "Big Screen Mode only. A Bomberman-style amphora maze — every alive player gets a satyr, a D-pad, and an amphora button on their phone; the whole board's on the TV. Getting splashed traps you in a bubble for 5 seconds instead of instant elimination — pop free if left alone, or get popped for good if an opponent finds you first. Last satyr standing wins." },
  laurelthief: { label: "Laurel Thief", icon: "🌿", rank: "score-desc", defaultDurationSec: 300, category: "Speed", blurb: "Everyone starts with 10 laurels. Tap another player to steal one — a short cooldown between steals, scaled to this Battle's own length. Lose all your laurels and you're out. Whoever's holding the most when time's up wins." },
  laurelthieftv: { label: "Laurel Thief — Big Screen", icon: "📺🌿", rank: "score-desc", defaultDurationSec: 120, category: "Speed", blurb: "Big Screen Mode only. Same steal-a-laurel battle, but the live picture — everyone's count, who's stealing from whom — shows on the shared TV while your phone stays a pure \"tap to steal\" grid. 5-second cooldown between steals, 2-minute battle." },
  wagertriviatv: { label: "Wager Trivia — Big Screen", icon: "🎲", rank: "score-desc", defaultDurationSec: 480, category: "Trivia", blurb: "Big Screen Mode only. Each round, a category and difficulty show on the TV before the question does — opt in or stay safe on your own phone, blind. Opt in and the question reveals: get it right, gain the round's points; get it wrong (or never answer), lose them. Score can go negative. Runs as many rounds as the Battle allows." },
  tartarustreadmill: { label: "Tartarus Treadmill — Big Screen", icon: "🌀", rank: "score-desc", defaultDurationSec: 300, category: "Speed", blurb: "Big Screen Mode only. A conveyor belt runs the length of the shared screen — cross the far edge and you've fallen into Tartarus. Push left or right from your phone to fight (or ride) the belt, and jump to dodge falling debris. Bump into another player and you both get shoved further along, not just blocked. The belt reverses without warning and speeds up over time. Last one standing wins." },
  spyfall: { label: "Spyfall", icon: "🕵️", rank: "score-desc", defaultDurationSec: 900, category: "Social", blurb: "Played live, out loud, same as the real board game (boardgamegeek.com/boardgame/166384) — the app just deals secret roles and referees. Everyone gets the same secret location except one random Spy. Ask each other questions to smoke out the Spy without giving the location away. Accuse someone and get full, active agreement from everyone else and — if you're right — the Spy is out; get it wrong and the accuser pays instead. The Spy can self-reveal and guess the location to win outright. Re-deals a fresh round after every resolution until only 3 players remain — those three are the winners." },
  acrophobia: { label: "Acrophobia — Big Screen", icon: "🔤", rank: "score-desc", defaultDurationSec: 480, category: "Party", blurb: "Big Screen Mode only. A clone of the classic party game. A random string of letters shows on the TV — everyone privately writes a phrase whose words start with those letters, in order. The phrases go up anonymously on the big screen for the room to vote on. Most votes wins a bonus on top of a point per vote. Fresh letters, next round, for as long as the Battle runs." },
  minigolf: { label: "Real-Time Mini Golf — Big Screen", icon: "⛳", rank: "score-desc", defaultDurationSec: 420, category: "Precision", blurb: "Big Screen Mode only. Everyone's ball rolls on the same obstacle course, shown live on the shared screen — your phone is just the club. Drag back and release to putt (like a slingshot) whenever your own ball is at rest; there are no turns, so several balls can be rolling at once. Bank shots off bumpers, thread a narrow gate, and time a pass through a rotating windmill blade and a sliding gate. First three balls to reach the hole win." },
  boggle: { label: "Boggle", icon: "🔠", rank: "score-desc", defaultDurationSec: 180, category: "Word", blurb: "3 flat minutes to trace adjacent letters into words on a 4x4 board. Standard length-based scoring — highest total wins." },
  dealornodeal: { label: "Deal or No Deal", icon: "💼", rank: "score-desc", defaultDurationSec: 420, category: "Luck", blurb: "Pick a case, open others for banker offers, and decide when to walk away. Highest dollar amount wins." },
  metronome: { label: "Metronome", icon: "🥁", rank: "score-desc", defaultDurationSec: 180, category: "Precision", blurb: "Hear an odd rhythm 3 times, then tap it back from memory. Closer to on-rhythm (same beat pattern for everyone) wins." },
  pit: { label: "The Agora", icon: "🏺", rank: "score-desc", defaultDurationSec: 480, category: "Negotiation", blurb: "Blind-trade cards of godly item sets with everyone else — offer 1-4 at a time, swap the instant someone offers the same count. First 3 to hold all 9 of one set win." },
  whosaidit: { label: "Who Said It?", icon: "💬", rank: "score-desc", defaultDurationSec: 180, category: "Trivia", blurb: "8 real quotes pulled from Panopticon chat — guess who said each one. Most correct wins." },
  masquerade: { label: "Murder at the Masquerade", icon: "🍷", rank: "score-desc", defaultDurationSec: 600, category: "Negotiation", blurb: "One active player secretly poisons one of two glasses and offers a target either one — the target picks what they drink, the active player's stuck with the rest. Two poison strikes and you're out. Last one standing wins." },
  closeto20: { label: "Close to 20", icon: "🐷", rank: "score-desc", defaultDurationSec: 480, category: "Prediction", blurb: "Everyone gets 13 coins and, on their turn, deposits all of them across at least 2 piggy banks (their own or others'). Go over 20 in your own bank and you're busted. Closest to 20 without going over wins." },
  snake: { label: "Snake", icon: "🐍", rank: "score-desc", defaultDurationSec: 180, category: "Arcade", blurb: "Classic Snake — eat food to grow, don't hit the walls or yourself. Speeds up as you go. Highest score wins." },
  minesweeper: { label: "Minesweeper", icon: "💣", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "Classic 9x9, 10-mine board, first click always safe. Clear it as fast as you can — cleared it wins by speed, didn't clear it ranks by how much you revealed." },
  stroop: { label: "Colorful Language", icon: "🌈", rank: "score-desc", defaultDurationSec: 240, category: "Visual", blurb: "20 color-name words, each printed in a mismatched ink color. Every tile asks for something different — sometimes the color it's printed in, sometimes the word it says — read each prompt. Same wall and sequence for everyone. Clear it fastest wins; a wrong answer costs time." },
  redlightgreenlight: { label: "Red Light, Green Light", icon: "🚦", rank: "score-desc", defaultDurationSec: 180, category: "Speed", blurb: "Same red/green sequence for everyone. Tap fast on green to score, don't tap on red — that costs a life (3 total). First to 100 wins outright; otherwise it's whoever scored highest." },
  sandsoftime: { label: "Sands of Time", icon: "⏳", rank: "score-desc", defaultDurationSec: 300, category: "Endurance", blurb: "Four hourglasses (10-60s each) run at once — re-flip one once it's at least 60% drained to keep it going. Every flip fades that hourglass further, until after 5 it's invisible and you're timing it blind. Let any one fully run out and it's over, everything's revealed, and your time locked in — the longer you last, the higher you rank." },
  slidingpuzzle: { label: "Sliding Puzzle", icon: "🧩", rank: "score-desc", defaultDurationSec: 240, category: "Puzzle", blurb: "Classic 8-puzzle — slide tiles into the empty slot to get them back in order, 1 to 8. Same scramble for everyone, guaranteed solvable. Fastest solve wins; ran out of time ranks by how many tiles were placed correctly." },
  lifestapestry: { label: "Life's a Tapestry", icon: "🧵", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "A woven picture has been cut into a grid and scrambled like a real over/under weave — each arrow only shifts the alternating checkerboard squares belonging to that row or column's own thread (they wrap around), not the whole row or column. Shift them back to rebuild the weaving shown on the side, then tap Check This. Same scramble for everyone, guaranteed solvable. Fastest solve wins; ran out of time ranks by how many squares were in place." },
  lifestapestrytv: { label: "Life's a Tapestry — Big Screen", icon: "📺🧵", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "Big Screen Mode only. Identical to Life's a Tapestry, except the reference weaving only ever shows on the TV — your phone is just the grid and its shift arrows, so you'll need to actually look up. Same scramble for everyone, guaranteed solvable. Fastest solve wins; ran out of time ranks by how many squares were in place." },
  torched: { label: "Torched", icon: "🔥", rank: "score-desc", defaultDurationSec: 360, category: "Prediction", blurb: "Everyone secretly hides a 3-cell marker on one shared grid. Once placement's done, players take turns calling out coordinates — land on someone's marker and their whole thing goes up in flames, eliminating them on the spot. Last marker standing wins; everyone else is ranked by how long they survived." },
  chains: { label: "Chains", icon: "✊", rank: "score-desc", defaultDurationSec: 300, category: "Negotiation", blurb: "Every player builds their own private order to face everyone else, picking rock, paper, or scissors against each — completely independent of what anyone else chooses or how they've ordered their own chain. Once everyone's locked in, chains play out: a win keeps yours going, a draw doesn't score but doesn't stop you either, a loss ends it right there. Highest score wins; ties go to whoever locked in first." },
  labyrinth: { label: "The Labyrinth", icon: "🐂", rank: "score-desc", defaultDurationSec: 240, config: { size: 13 }, category: "Maze", blurb: "Navigate a maze collecting scattered olives while the Minotaur hunts you down — it recalculates the shortest path to wherever you actually are every single step, so there's no outrunning it by luck. Clear every olive before it catches you for the best possible finish; otherwise, whoever collected the most before getting caught (or before time runs out) ranks highest." },
  oraclesseal: { label: "The Oracle's Seal", icon: "🏺", rank: "score-desc", defaultDurationSec: 180, category: "Precision", blurb: "Trace a shape stamped into a fragile clay tablet, from start back around to start — stray off the outline or lift your finger before you're done and it cracks. Too many cracks and the whole tablet shatters. Finish clean and it's a race against the clock; shatter first and you're ranked by how much of the outline you completed." },
  scavengerhunt: { label: "Scavenger Hunt", icon: "🏺", rank: "score-desc", defaultDurationSec: 600, category: "Negotiation", blurb: "Race between 8 temples collecting a set of 8 sacred offerings — each temple's stock is fixed and shared, first come first served, gone for good once someone takes it. Collect one of everything and return to Mount Olympus; the first 3 to do it win outright, everyone else is ranked by how much of the set they'd completed." },
  hue: { label: "Hue", icon: "🎨", rank: "score-desc", defaultDurationSec: 120, category: "Visual", blurb: "Mix red, green, and blue sliders to recreate a target color entirely by eye — no live closeness score while you're mixing, just your own swatch to compare. Lock in when you're happy with it. Scored on how close you land, with a small bonus for locking in quickly." },
  operator: { label: "Operator", icon: "🧮", rank: "score-desc", defaultDurationSec: 180, category: "Puzzle", blurb: "Combine five numbers with +, −, ×, and ÷ to hit a hidden target — tap a number, an operator, then another number, and the result becomes a new tile to keep working with. Undo or reset if you get stuck. Scored purely on speed — fastest to the target wins." },
  tavo: { label: "Pandora's Moving Company", icon: "📦", rank: "score-desc", defaultDurationSec: 180, category: "Puzzle", blurb: "Push crates onto their markers — walk into a crate to shove it one square, but you can only push, never pull, so plan your order before you move. Every board is guaranteed solvable. Undo and Reset are both free of penalty; mostly the clock decides your score, with a small bonus for a clean, efficient line." },
  tangle: { label: "Tangle", icon: "🪢", rank: "score-desc", defaultDurationSec: 150, category: "Puzzle", blurb: "Dots joined by strings, some crossing (shown in red) — drag the dots until no strings cross at all. Every knot here is guaranteed fully untangleable. Re-scramble resets the layout but keeps the clock running. Your time is your score — the faster you untangle it, the better." },
  bloom: { label: "Bloom", icon: "🌸", rank: "score-desc", defaultDurationSec: 180, category: "Puzzle", blurb: "The board blooms from a glowing center patch — tap a hue and the patch floods to that color, absorbing every connected cell that matches. Keep sweeping until the whole board is one light. No clock pressure — scored on how few sweeps it takes." },
  hermesgrasp: { label: "Hermes' Grasp", icon: "🪽", rank: "score-desc", defaultDurationSec: 150, category: "Speed", blurb: "8 cards, same deck for everyone: two of five sacred relics shown, each in some color — not necessarily its own. Exactly one shown in its true color? Grab that one. Neither is? Grab the one relic (of the three not shown at all) whose object and true color are both missing from the card. Fastest through all 8 wins; a wrong grab costs time." },
  pandorasboxes: { label: "Pandora's Boxes", icon: "⚱️", rank: "score-desc", defaultDurationSec: 420, category: "Negotiation", blurb: "Everyone starts holding a sealed box. Give yours away to another player; whatever you receive in return must be given away again next round — just never back to whoever it came from. Once every second gift is locked in, every box opens at once: three hold the season's fortune (1st, 2nd, 3rd), the rest hold nothing." },
  musicalchairs: { label: "Musical Chairs", icon: "🎵", rank: "score-desc", defaultDurationSec: 360, category: "Speed", blurb: "One chair fewer than players, every round, exactly like the real thing. Music plays for an unpredictable stretch, then stops — grab a chair before they're gone. Whoever's left standing is out. Last one seated wins." },
  musicalchairstv: { label: "Musical Chairs — Big Screen", icon: "📺🎵", rank: "score-desc", defaultDurationSec: 360, category: "Speed", blurb: "Big Screen Mode only. One trivia question on the TV each round, several answers on your phone. A correct answer claims one of the (always one-fewer-than-players) open chairs — first come, first served. A wrong answer locks you out for a few seconds. Whoever's chairless when they run out is eliminated." },
  floor: { label: "The Floor", icon: "🏛️", rank: "score-desc", defaultDurationSec: 900, category: "Trivia", blurb: "Everyone claims a square with their own pre-chosen area of expertise. Adjacent players duel over a question from one of their two categories — miss it and your entire territory transfers to the winner, who picks their next target from whoever's now touching their ground. Last one holding any territory takes the whole floor." },
  basketball: { label: "Basketball", icon: "🏀", rank: "score-desc", defaultDurationSec: 180, config: { lives: 3 }, category: "Arcade", blurb: "A classic swipe-to-shoot hoops game — swipe up on the ball to shoot, 3 misses and you're done. Score enough baskets and the hoop starts moving: first sliding side to side, then roaming anywhere on the court. A clean swish is worth more than a rim-in or a bank shot off the backboard. Most points wins." },
  stack: { label: "Stack", icon: "🏗️", rank: "score-desc", defaultDurationSec: 180, category: "Arcade", blurb: "A block slides back and forth above your tower — tap to drop it. Land it flush for a perfect stack (no shrinkage, builds a combo); land it offset and only the overlap survives, narrowing the tower for next time. One total miss ends it. Rendered in true isometric 3D, colors drifting warmer the higher you climb. Speed ramps up the higher you get. Tallest tower wins." },
  stockmarket: { label: "Stock Market", icon: "📈", rank: "score-desc", defaultDurationSec: 3600, category: "Finance", blurb: "$10,000 to trade real companies at real, live prices for the length of the battle — starts with 6 well-known stocks, but search adds any real US stock to the shared watchlist (up to 20 total). Highest final profit wins. Only ever offered when the battle's own hours overlap real stock market trading hours." },
  artauction: { label: "Art Auction", icon: "🎨", rank: "score-desc", defaultDurationSec: 600, category: "Negotiation", blurb: "Everyone paints something, then every piece goes up in one simultaneous, anonymous silent auction — nobody knows who painted what, and nobody sees anyone's bids until everything closes at once. Whoever ends up owning the most pieces wins; ties go to whoever has the most between leftover money and what their own piece sold for." },
  seasontrivia: { label: "Season Trivia", icon: "📜", rank: "score-desc", defaultDurationSec: 300, category: "Trivia", locksCeremonyTab: true, blurb: "A quiz about THIS season — who won which Battle, who got exiled when — generated fresh from the game's own real history, not a generic question bank. The Ceremony tab is locked while this runs, since its recap would just hand out the answers. Needs a few completed rounds of history to draw from." },
  timeline: { label: "Timeline", icon: "🕰️", rank: "score-desc", defaultDurationSec: 300, category: "Trivia", locksCeremonyTab: true, blurb: "Put this season's real events back in the order they actually happened — Battles won, players exiled, all pulled from the game's own real history. Scored on how many end up in the exact right spot. The Ceremony tab is locked while this runs, since its recap would just hand out the answer. Needs a few completed rounds of history to draw from." },
  // Deliberately not described here, on purpose — see
  // lib/games/mysteryButtonData.js's own header comment. This blurb is
  // exactly what shows up on the rules page (see lib/rulesContent.js's
  // battleList/HelpPanel.jsx), so leaving it at "[REDACTED]" is what
  // actually keeps the rules a mystery, not just a note that says so.
  mysterybutton: { label: "Mystery Button", icon: "🔴", rank: "score-desc", defaultDurationSec: 300, category: "Luck", blurb: "[REDACTED]" },
  pegasusflight: { label: "Pegasus's Flight", icon: "🪽", rank: "score-desc", defaultDurationSec: 180, config: { lives: 3 }, category: "Arcade", blurb: "A Greek-mythology Flappy Bird — tap to flap Pegasus between pairs of marble columns, one point per column cleared, +5 for a lightning bolt snagged mid-gap. Three crashes and you're grounded. Gaps narrow and the scroll speeds up the higher your score climbs. Most points wins." },
  goldenfleece: { label: "The Golden Fleece — Big Screen", icon: "🐑", rank: "score-desc", defaultDurationSec: 600, category: "Luck", blurb: "Big Screen Mode only. A Greek-mythology retelling of the classic press-your-luck game Diamant/Incan Gold (boardgamegeek.com/boardgame/15512) — everyone delves the same monster-guarded ruin, shown on the TV, one card at a time. Treasure splits evenly among whoever's still inside; a monster's first sighting is just a scare, its second empties every hand still in the ruin. After each card, secretly press on or turn back — turning back banks what you're carrying for good, and if you're the ONLY one who turns back that moment, you also grab any Golden Fleece shard sitting on the path. Runs 3 chambers, everyone starting fresh each time. Highest total banked wins." },
  riverstyx: { label: "River Styx — Big Screen", icon: "💀🌊", rank: "score-desc", defaultDurationSec: 720, category: "Strategy", blurb: "Big Screen Mode only. A Greek-mythology retelling of the classic tile game Tsuro (boardgamegeek.com/boardgame/2513) — the shared 6x6 board and everyone's shade crossing the Styx show on the TV, your phone is just your own 3-tile hand. On your turn, place and rotate one tile into the cell your shade already faces, and it — and anyone else waiting on that same cell — slides along the newly-connected paths until it exits the board (eliminated), reaches an empty cell (waits), or collides with another shade (both eliminated). Last shade standing wins; everyone vanishing on the same placement, or the deck and every hand running dry with 2+ shades still crossing, is a shared victory." },
  winedarksea: { label: "The Wine-Dark Sea — Big Screen", icon: "🌀🚢", rank: "score-desc", defaultDurationSec: 780, category: "Strategy", blurb: "Big Screen Mode only. A Greek-mythology retelling of Tsuro of the Seas (boardgamegeek.com/boardgame/79066), the expansion to Tsuro — same shared-board tile-laying as River Styx, but with ships instead of shades and a far bigger pool of wake tiles. After each ship's own move, Charybdis — a roaming whirlpool — has roughly a 3-in-8 chance of lurching a cell and dragging under any ship on or beside where she lands. Last ship afloat wins; a shared wipeout or full tile exhaustion with 2+ ships still sailing is a shared victory." },
  minotaurmaze: { label: "The Labyrinth of the Minotaur", icon: "🐂", rank: "score-desc", defaultDurationSec: 150, config: { size: 10 }, category: "Maze", blurb: "Tilt your phone to roll a ball through a randomly generated maze — your own maze, guaranteed solvable, different from everyone else's — from the entrance to the exit before the Minotaur catches you. Uses your phone's motion sensors; devices without them (or where you decline the permission prompt) get on-screen directional buttons instead. Escape and your finish time is your score; still inside when time runs out and you're ranked by how far through the maze you got." },
  majorityrules: { label: "Majority Rules", icon: "🗳️", rank: "score-desc", defaultDurationSec: 300, category: "Social", blurb: "8 forced-choice questions land at once, each one pitting two of your fellow alive players against each other (\"Who is funnier — X or Y?\"). Answer all 8 privately and lock them in — no hints, no tallies, chat's even locked until you do. The reveal — who the room's majority actually picked, and how you did against it — only shows up later, on the History tab. Most answers matching the majority wins." },
  majorityrulestv: { label: "Majority Rules — Big Screen", icon: "📺🗳️", rank: "score-desc", defaultDurationSec: 600, category: "Social", blurb: "Big Screen Mode only. Same forced-choice questions as the regular version, but one at a time, live: everyone answers on their phone, then the big screen reveals the vote split and who matched the room's majority before moving to the next. After 8 questions, tied leaders go to sudden death — one extra question at a time until the tie breaks (or a generous cap is reached). Most majority matches wins." },
  triggerhappy: { label: "Trigger Happy", icon: "🎚️", rank: "score-desc", defaultDurationSec: 240, category: "Puzzle", blurb: "A grid of the 5 Hermes' Grasp relics is scattered across 20 cells — study it as long as you like, then pull the lever to blank the whole thing and place every relic back exactly where it was, from memory. Most cells correct wins; a tie goes to whoever replicated fastest." },
  triggerhappytv: { label: "Trigger Happy — Big Screen", icon: "📺🎚️", rank: "score-desc", defaultDurationSec: 480, category: "Puzzle", blurb: "Big Screen Mode only. Same memory game as Trigger Happy, but head-to-head: two players study the same 15-cell grid on the TV, then race to replicate it from memory on their own phones the instant either of them pulls the lever. Most accurate replication wins the duel (fastest breaks a tie); the winner picks the next two to face off. Runs as many duels as the Battle allows — most duel wins takes it." },
  godsandgambits: { label: "Gods and Gambits — Big Screen", icon: "🏺", rank: "score-desc", defaultDurationSec: 540, category: "Luck", blurb: "Big Screen Mode only. A Greek-mythology retelling of Wits & Wagers (Vegas Edition) (boardgamegeek.com/boardgame/29223), trimmed to 3 rounds. The Oracle poses a numeric riddle each round — everyone privately writes their own guess, then the guesses sort low-to-high onto a shared betting board on the TV, distinct values sharing a space, longer-odds the further out the guess. Place up to 2 bets, in drachma, from your own running bankroll, on any space — your own guess, someone else's, or the highest-odds space betting the truth falls under every guess submitted. The true answer then reveals: the guess closest to it WITHOUT going over wins the board, paying out every bet on that space; whoever actually submitted that guess also splits a flat bonus pot outright. Bankrolls carry over and compound across all 3 rounds — richest coffer when the Oracle falls silent wins." },
  // Generous default length (900s, on the long end of this app's
  // typical range) is deliberate: unlike the physical board game this
  // is reskinned from, this version has NO player-count cap (see
  // lib/games/divinersDiceData.js's own header), and more players
  // sharing one turn order means more real time needed before anyone
  // gets a satisfying number of turns — a 6-player table needs roughly
  // twice the wall-clock of a 3-player one for the same number of
  // rolls each. lib/roundEngine.js's housekeeping tick (not just a
  // fixed round count, since this game has none) is what actually
  // keeps it from running past this outer timer regardless.
  divinersdice: { label: "The Diviner's Dice — Big Screen", icon: "🔮", rank: "score-desc", defaultDurationSec: 900, category: "Luck", blurb: "Big Screen Mode only. A Greek-mythology retelling of the dice game Qwixx (boardgamegeek.com/boardgame/63268) — no player cap, unlike the physical game. Four omen-tracks (Ares, Apollo, Demeter, Poseidon), each running 2 through 12 in its own direction. Each roll, EVERY player may mark the two white dice's sum in one of their own tracks; the active player alone gets one more optional mark, combining one white die with one colored die. Marks in a track must always move strictly further along it — skip a number and it's gone for good. A track's final number needs 5 prior marks to reach, and marking it locks that track for everyone's dice pool for the rest of the game. Mark nothing at all on your own turn and take a 5-point penalty; 4 penalties for one player, or 2 locked tracks total, ends it. Highest score (a rising table per track, minus penalties) wins." },
  splitfriction: { label: "Split Friction", icon: "⚔️", rank: "score-desc", defaultDurationSec: 540, category: "Negotiation", blurb: "An offering of oaths to every other living player at once — everyone privately proposes their own split of 100 points to each of their rivals (how much they keep, how much they hand over), then reviews every split proposed to them in return and accepts or rejects each one on its own. Accept a split and both sides of that exact deal are paid out; reject it and neither side sees a point from it — your own dealings with anyone else are never affected either way. Highest total actually collected wins." },
  crowns: { label: "Crowns", icon: "👑", rank: "score-desc", defaultDurationSec: 540, category: "Negotiation", blurb: "Everyone starts holding one unique god-crested crown — every player's holdings are always fully visible to everyone else. Propose a direct trade to anyone: one specific crown of yours for one specific crown of theirs; they accept or decline. It's a checklist, not a snapshot: the first to have EVER held every crown in the set at some point wins outright, whether or not they still hold them all. If time runs out first, whoever's checklist has the most crowns ever collected wins instead." },
  crownstv: { label: "Crowns — Big Screen", icon: "📺👑", rank: "score-desc", defaultDurationSec: 600, category: "Negotiation", blurb: "Big Screen Mode only. Identical to Crowns, except every player's current holdings, checklist progress, and the live trade feed also show on the shared TV. First to have EVER held every crown wins outright; if time runs out, whoever's checklist has the most crowns ever collected wins instead." },
  poseidonspool: { label: "Poseidon's Pool", icon: "🎱", rank: "score-desc", defaultDurationSec: 480, category: "Precision", blurb: "Everyone's own ball sits on a shared pool table and doubles as their cue ball. Drag back to aim and set power, then let go to shoot — knock another player's ball into a pocket and they're eliminated, including yourself if you scratch. A short reload between your own shots. Last ball on the table wins." },
  poseidonspooltv: { label: "Poseidon's Pool — Big Screen", icon: "📺🎱", rank: "score-desc", defaultDurationSec: 600, category: "Precision", blurb: "Big Screen Mode only. Identical to Poseidon's Pool, except the table itself only lives on the shared TV — your phone is purely aim and power. Knock another player's ball into a pocket to eliminate them, including your own ball on a scratch. Last ball standing wins." },
  pythiasdice: { label: "The Pythia's Dice", icon: "🔮", rank: "score-desc", defaultDurationSec: 480, category: "Luck", blurb: "Solo, asynchronous Yahtzee — 13 rounds, your own 5 dice, up to 2 rerolls each round, your choice which to hold. Assign each roll to one of 13 categories on your own scorecard (upper numbers, three/four of a kind, full house, straights, Yahtzee, chance); an unusable roll can still be zeroed out into any open category. 63+ across the upper section earns a 35-point bonus, and any Yahtzee after your first earns a 100-point bonus. Highest total when all 13 categories are filled (or time runs out) wins." },
  naiadsaqueduct: { label: "Naiads' Aqueduct", icon: "🏺", rank: "score-desc", defaultDurationSec: 300, config: { size: 8 }, category: "Puzzle", blurb: "The classic rotate-the-tiles pipe puzzle, reskinned as a Greek aqueduct — tap a channel to spin it 90° until every one connects, spring to every corner, with no dead ends facing the wrong way. Same grid for everyone, guaranteed solvable. Fastest full connection wins; ran out of time ranks by how many channels were correctly aligned." },
  panspanic: { label: "Pan's Panic", icon: "😱", rank: "score-desc", defaultDurationSec: 180, config: { lives: 3 }, category: "Speed", blurb: "A Greek-mythology retelling of the classic mobile game Chicken Scream — scream into your mic to run, a sudden louder burst to leap a chasm (keep screaming mid-air or you'll land short and fall in), and go dead silent to slip past a herm statue blocking the path without knocking it flat. No mic, denied permission, or a quiet room — a press-and-hold Scream button takes over automatically. Three falls and you're out. Highest score (distance run plus a bonus per obstacle cleared) wins." },
  delphisdig: { label: "Delphi's Dig", icon: "⛏️", rank: "score-desc", defaultDurationSec: 300, category: "Puzzle", blurb: "6 buried equations, 3 columns of dirt piles. Tap a pile once to see whose sigil marks it, tap it again to unearth the number or operator underneath — but only one pile ever stays uncovered at a time, so digging anywhere else buries it right back. Every fragment sharing a sigil belongs to one equation, and its three pieces are scattered to different rows, one per column, so it's real memory work to track down all three. Once you have, work out the answer and submit it. Same board for everyone. Solve all 6 fastest wins; a wrong guess costs a little, ran out of time ranks by how many you solved." },
  midashoard: { label: "Midas's Hoard", icon: "💰", rank: "score-desc", defaultDurationSec: 600, category: "Prediction", blurb: "Big Screen Mode only. King Midas's vault is heaped with a fresh pile of cursed golden trinkets, shown on the TV — everyone privately guesses the count on their own phone. Once every guess is in, they reveal on the big screen and each guesser chooses to stay near the hoard or fold back to safety. Folding is always safe. Among whoever stayed: the closest guess scores a point, the single farthest guess is turned to gold — eliminated on the spot. First to 3 points, or the last player never turned to gold, wins." },
  chariots: { label: "Chariots of Conspire", icon: "🐎", rank: "score-desc", defaultDurationSec: 240, category: "Chaos", blurb: "Big Screen Mode only. Three players start seated in three chariots — everyone else is on foot. While the chariots roll, outsiders can pull to speed them toward the next stop (pull hard and stops come fast; do nothing and they come slow). At each stop, outsiders can search bushes — 2 hide a magic rein that lets you kick a rider out and take their seat on the spot. Whoever's seated when the Battle ends are the three winners, with 1st/2nd/3rd revealed at random right at the finish." },
  scyllasstrait: { label: "Scylla's Strait", icon: "🐙", rank: "score-desc", defaultDurationSec: 600, category: "Strategy", blurb: "Big Screen Mode only. Everyone's boat lines up single-file through a narrow strait with the monster Scylla lurking behind the last one. Each round, privately play a numbered card — the lowest number to go unmatched moves to the front first, then the next-lowest, and so on, so the highest number to go unmatched ends up safest of all. Tie someone's number and you don't move at all. Whoever ends up last gets an item snatched by Scylla (but is flung to the front and gets every played card back) — lose all 4 items and you're out. Once only two boats remain, Scylla takes the back one immediately and the front one wins." },
};

export function gameConfigWithDefaults(gameType, overrides) {
  const base = GAME_REGISTRY[gameType]?.config || {};
  return { ...base, ...(overrides || {}) };
}
